---
- name: Configuring a NFS-Server and Client
  hosts: nfs_server
  tasks:
    - name: Configuring a NFS-server
      include_role:
        name: nfs-server
      when: inventory_hostname == "system1" 

    - name: Configuring a NFS-client
      mount: 
        src: system1:/nfs_share
        path: "/mount/nfs"
        state: mounted
        opts: "defaults,_netdev"
        fstype: nfs
      when: inventory_hostname == "system2"

