---
- name: Configuring a Slave bind DNS server
  hosts: slave_dns
  vars_files:
    - ./defaults.yml
    - ./slave-vars.yml
  tasks:
  - name: Installing a Required packages
    yum:
      name: "{{ item }}"
      state: present
    loop: "{{ pkgs }}"

  - name: Configuring a configuration file
    template:
      src: ./slave-named.conf.j2
      dest: "{{ conf_dir }}/named.conf"

  - name: Configuring a SELINUX
    selinux:
      policy: targeted
      state: permissive

  - name: Starting a services
    service:
      name: "{{ item }}"
      state: restarted
      enabled: true
    loop: "{{ srvs }}"

  - name: Configuring a firewalle rules
    firewalld:
      service: dns
      permanent: true
      state: enabled
      immediate: true

