---
- name: INSTALLING A REQUIRED PACKAGES
  yum:
    name: 
      - nfs-utils
      - rpcbind
    state: present
  
- name: IS NFS SHARE EXIST?
  file:
    path: "{{ nfs_share }}"
    mode: "0777"
    state: directory
   
- name: MAKE SURE NFS SHARE HAVE SOME FILES ETC...
  copy:
    src: "{{ item }}"
    dest: "{{ nfs_share }}"
    remote_src: no
  with_fileglob:
    - /etc/*.conf

- name: EXPORTING NFS SHARE.....
  template:
    src: exports.j2
    dest: /etc/exports

- name: SERVICE START & ENABLED
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop: "{{ srvs }}"

- name: PREPARE FIREWALL
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop:
    - nfs
    - rpc-bind
    - mountd    

- name: SELINUX BE PERMISSIVE
  selinux:
    policy: targeted
    state: permissive


