---
- name: SETUP NIS
  hosts: nis-systems
  become: true
  tasks:
    - name: CONFIGURING A NIS
      when: ( ansible_distribution | lower in ['centos','redhat'] ) and ansible_distribution_major_version == '7'
      block:
        - name: CONFIGURING A NIS-SERVER
          include_role:
            name: nis-server
          when: inventory_hostname in groups['nis-server']
        - name: CONFIGURING A NIS-CLIENT
          include_role:
            name: nis-client
          when: inventory_hostname in groups['nis-client']
      ignore_errors: true
