---
- name: Installing a required packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"

- name: INstall pexpect
  pip:
    name: pexpect
    executable: pip3.6

- name: Starting a services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - ypserv
    - nfs-server
    - rpcbind
    - yppasswdd
    - ypbind
    - firewalld
    - xinetd

- name: Setting up a hostname
  hostname:
    name: "{{ nis_server_hostname }}"

- name: Setting up a ypdomainname
  command: "ypdomainname {{ nis_domain }}"

- name: Permanent network setup
  template:
    src: network.j2
    dest: /etc/sysconfig/network

- name: hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Secure networks
  template:
    src: securenets.j2
    dest: /var/yp/securenets

- name: Initializing a nis-server
  expect:
    command: /usr/lib64/yp/ypinit -m
    responses:
      "next host to add:": "{{ nis_server_hostname }}.{{ nis_domain }}"
      "next host to add:": \400
      "Is this correct\\? \\[y/n:\\]": "y"
        #register: ypinit_output
        #changed_when: "'failed' not in ypinit_output.stderr.lower()"
      
- name: Make NIS MAP
  command: make -C /var/yp

- name: making a yppasswdd file
  template: 
    src: yppasswdd.j2
    dest: /etc/sysconfig/yppasswdd
  notify: restart yppasswdd

- name: Configuring a firewall
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop:
    - "944/tcp"
    - "944/udp"
    - "945/tcp"
    - "945/udp"
    - "946/udp"

- name: Selinux ---> permissive
  selinux:
    policy: targeted
    state: permissive

